# Generated by Django 5.2 on 2025-09-14 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='reports/original/')),
                ('oim_json_file', models.FileField(blank=True, null=True, upload_to='reports/oim/')),
                ('entity', models.CharField(blank=True, max_length=255)),
                ('reporting_period', models.CharField(blank=True, max_length=255)),
                ('taxonomy_version', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('validated', 'Validated'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('validation_summary', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
