# Generated by Django 5.2 on 2025-09-14 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=512)),
                ('value', models.TextField(blank=True)),
                ('datatype', models.CharField(blank=True, max_length=256)),
                ('unit', models.CharField(blank=True, max_length=128)),
                ('context', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='api.report')),
            ],
            options={
                'indexes': [models.Index(fields=['report', 'concept'], name='api_fact_report__dffdcc_idx')],
            },
        ),
    ]
