# Generated by Django 5.2 on 2025-09-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_company_and_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='VsmeRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('entity_identifier', models.CharField(blank=True, max_length=255)),
                ('employees_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('employees_unit', models.CharField(blank=True, max_length=64)),
                ('ghg_total_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('ghg_total_unit', models.CharField(blank=True, max_length=64)),
                ('ghg_scope1_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('ghg_scope1_unit', models.CharField(blank=True, max_length=64)),
                ('ghg_scope2_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('ghg_scope2_unit', models.CharField(blank=True, max_length=64)),
                ('energy_consumption_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('energy_consumption_unit', models.CharField(blank=True, max_length=64)),
                ('renewable_energy_share_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('renewable_energy_share_unit', models.CharField(blank=True, max_length=32)),
                ('water_withdrawal_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('water_withdrawal_unit', models.CharField(blank=True, max_length=64)),
                ('water_discharge_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('water_discharge_unit', models.CharField(blank=True, max_length=64)),
                ('waste_generated_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('waste_generated_unit', models.CharField(blank=True, max_length=64)),
                ('hazardous_waste_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('hazardous_waste_unit', models.CharField(blank=True, max_length=64)),
                ('non_hazardous_waste_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('non_hazardous_waste_unit', models.CharField(blank=True, max_length=64)),
                ('completeness_score', models.PositiveSmallIntegerField(default=0)),
                ('source_concepts', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_rows', to='api.company')),
                ('last_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_rows', to='api.report')),
            ],
            options={'ordering': ['company__name', 'year']},
        ),
        migrations.AlterUniqueTogether(
            name='vsmeregister',
            unique_together={('company', 'year')},
        ),
    ]


